variables:
  DISTRIBUTION_TAG: "2020-07-06"

.kernel+rootfs:
  stage: container-2
  extends:
    - .ci-run-policy
  variables:
    GIT_STRATEGY: fetch
  script:
    - DEBIAN_ARCH=${DEBIAN_ARCH} .gitlab-ci/container/lava_arm.sh

kernel+rootfs_arm64:
  extends:
    - .use-arm_build
    - .kernel+rootfs
  tags:
    - aarch64
  variables:
    DEBIAN_ARCH: "arm64"

kernel+rootfs_armhf:
  extends:
    - kernel+rootfs_arm64
  variables:
    DEBIAN_ARCH: "armhf"

.lava-test:
  extends:
    - .ci-run-policy
  variables:
    GIT_STRATEGY: none # testing doesn't build anything from source
    ENV_VARS: "DEQP_PARALLEL=6"
    DEQP_VERSION: gles2
    ARTIFACTS_URL: "https://minio-packet.freedesktop.org/mesa-lava/${CI_PROJECT_PATH}/${DISTRIBUTION_TAG}/${ARCH}"
    MESA_URL: "https://minio-packet.freedesktop.org/artifacts/${CI_PROJECT_PATH}/${CI_PIPELINE_ID}/mesa-${ARCH}.tar.gz"
  script:
    - >
      artifacts/generate_lava.py \
        --template artifacts/lava-deqp.yml.jinja2 \
        --pipeline-info "$CI_PIPELINE_URL on $CI_COMMIT_REF_NAME ${CI_NODE_INDEX}/${CI_NODE_TOTAL}" \
        --base-artifacts-url ${ARTIFACTS_URL} \
        --mesa-url ${MESA_URL} \
        --device-type ${DEVICE_TYPE} \
        --env-vars "${ENV_VARS}" \
        --deqp-version ${DEQP_VERSION} \
        --kernel-image-name ${KERNEL_IMAGE_NAME} \
        --kernel-image-type "${KERNEL_IMAGE_TYPE}" \
        --gpu-version ${GPU_VERSION} \
        --boot-method ${BOOT_METHOD} \
        --lava-tags "${LAVA_TAGS}" \
        --ci-node-index "${CI_NODE_INDEX}" \
        --ci-node-total "${CI_NODE_TOTAL}"
    - lava_job_id=`lavacli jobs submit lava-deqp.yml` || lavacli jobs submit lava-deqp.yml
    - echo $lava_job_id
    - rm -rf artifacts/*
    - cp lava-deqp.yml artifacts/.
    - lavacli jobs logs $lava_job_id | tee artifacts/lava-deqp-$lava_job_id.log
    - lavacli jobs show $lava_job_id
    - result=`lavacli results $lava_job_id 0_deqp deqp | head -1`
    - echo $result
    - '[[ "$result" == "pass" ]]'
  artifacts:
    name: "mesa_${CI_JOB_NAME}"
    when: always
    paths:
      - artifacts/

.lava-test:armhf:
  variables:
    ARCH: armhf
    KERNEL_IMAGE_NAME: zImage
    KERNEL_IMAGE_TYPE: "type:\ zimage"
    BOOT_METHOD: u-boot
  extends:
    - .lava-test
    - .use-arm_build
  dependencies:
    - meson-armhf
  needs:
    - kernel+rootfs_armhf
    - meson-armhf

.lava-test:arm64:
  variables:
    ARCH: arm64
    KERNEL_IMAGE_NAME: Image
    KERNEL_IMAGE_TYPE: "type:\ image"
    BOOT_METHOD: u-boot
  extends:
    - .lava-test
    - .use-arm_build
  dependencies:
    - meson-arm64
  needs:
    - kernel+rootfs_arm64
    - meson-arm64

panfrost-t720-gles2:arm64:
  extends:
    - .lava-test:arm64
    - .panfrost-rules
  variables:
    DEVICE_TYPE: sun50i-h6-pine-h64
    GPU_VERSION: panfrost-t720
    ENV_VARS: "PAN_MESA_DEBUG=gles3 DEQP_PARALLEL=6 DEQP_EXPECTED_RENDERER=T720"
  tags:
    - mesa-ci-aarch64-lava-collabora

panfrost-t760-gles2:armhf:
  extends:
    - .lava-test:armhf
    - .panfrost-rules
  variables:
    DEVICE_TYPE: rk3288-veyron-jaq
    GPU_VERSION: panfrost-t760
    BOOT_METHOD: depthcharge
    KERNEL_IMAGE_TYPE: ""
    ENV_VARS: "PAN_MESA_DEBUG=gles3 DEQP_PARALLEL=6 DEQP_EXPECTED_RENDERER=T760"
  tags:
    - mesa-ci-aarch64-lava-collabora

panfrost-t860-gles2:arm64:
  extends:
    - .lava-test:arm64
    - .panfrost-rules
  variables:
    DEVICE_TYPE: rk3399-gru-kevin
    GPU_VERSION: panfrost-t860
    BOOT_METHOD: depthcharge
    KERNEL_IMAGE_TYPE: ""
    ENV_VARS: "PAN_MESA_DEBUG=gles3 DEQP_PARALLEL=6 DEQP_EXPECTED_RENDERER=T860"
  tags:
    - mesa-ci-aarch64-lava-collabora

panfrost-t860-gles3:arm64:
  extends:
    - .lava-test:arm64
    - .panfrost-rules
  variables:
    DEVICE_TYPE: rk3399-gru-kevin
    GPU_VERSION: panfrost-t860
    BOOT_METHOD: depthcharge
    KERNEL_IMAGE_TYPE: ""
    DEQP_VERSION: gles3
    ENV_VARS: "PAN_MESA_DEBUG=gles3 DEQP_PARALLEL=6 DEQP_EXPECTED_RENDERER=T860"
    CI_NODE_INDEX: 1
    CI_NODE_TOTAL: 5
  tags:
    - mesa-ci-aarch64-lava-collabora

.panfrost-t820-gles2:arm64:
  extends:
    - .lava-test:arm64
    - .panfrost-rules
  variables:
    DEVICE_TYPE: meson-gxm-khadas-vim2
    GPU_VERSION: panfrost-t820
    LAVA_TAGS: panfrost
    ENV_VARS: "PAN_MESA_DEBUG=gles3 DEQP_PARALLEL=6 DEQP_EXPECTED_RENDERER=T820"
  tags:
    - mesa-ci-aarch64-lava-baylibre

.lima-mali400-test:armhf:
  parallel: 2
  extends:
    - .lava-test:armhf
    - .lima-rules
  variables:
    DEVICE_TYPE: sun8i-h3-libretech-all-h3-cc
    GPU_VERSION: lima
    ENV_VARS: "DEQP_PARALLEL=3 DEQP_EXPECTED_RENDERER=Mali400"
  tags:
    - mesa-ci-aarch64-lava-baylibre

.lima-mali450-test:arm64:
  extends:
    - .lava-test:arm64
    - .lima-rules
  variables:
    DEVICE_TYPE: meson-gxl-s905x-libretech-cc
    GPU_VERSION: lima
    ENV_VARS: "DEQP_PARALLEL=6 DEQP_EXPECTED_RENDERER=Mali450"
  tags:
    - mesa-ci-aarch64-lava-baylibre
